//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABI_Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class abiexam_dbEntities : DbContext
    {
        public abiexam_dbEntities()
            : base("name=abiexam_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer> answers { get; set; }
        public virtual DbSet<chairman> chairmen { get; set; }
        public virtual DbSet<exam> exams { get; set; }
        public virtual DbSet<exam_chairman> exam_chairman { get; set; }
        public virtual DbSet<exam_examinee> exam_examinee { get; set; }
        public virtual DbSet<exam_practice_type> exam_practice_type { get; set; }
        public virtual DbSet<exam_question> exam_question { get; set; }
        public virtual DbSet<exam_version> exam_version { get; set; }
        public virtual DbSet<examinee> examinees { get; set; }
        public virtual DbSet<examinee_answer> examinee_answer { get; set; }
        public virtual DbSet<off_question_map_t2> off_question_map_t2 { get; set; }
        public virtual DbSet<off_question_type_l1> off_question_type_l1 { get; set; }
        public virtual DbSet<off_question_type_l2> off_question_type_l2 { get; set; }
        public virtual DbSet<off_question_version> off_question_version { get; set; }
        public virtual DbSet<office_question> office_question { get; set; }
        public virtual DbSet<office_version> office_version { get; set; }
        public virtual DbSet<practice_type> practice_type { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
