//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABI_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class off_question_map_t2
    {
        public int id { get; set; }
        public int question_id { get; set; }
        public int type_l2_id { get; set; }
        public System.DateTime create_at { get; set; }
    
        public virtual off_question_type_l2 off_question_type_l2 { get; set; }
        public virtual office_question office_question { get; set; }
    }
}
