//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABI_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class off_question_type_l1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public off_question_type_l1()
        {
            this.off_question_type_l2 = new HashSet<off_question_type_l2>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int practice_id { get; set; }
        public string description { get; set; }
        public System.DateTime create_at { get; set; }
    
        public virtual practice_type practice_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<off_question_type_l2> off_question_type_l2 { get; set; }
    }
}
