//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABI_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class office_question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public office_question()
        {
            this.exam_question = new HashSet<exam_question>();
            this.examinee_answer = new HashSet<examinee_answer>();
            this.off_question_map_t2 = new HashSet<off_question_map_t2>();
            this.off_question_version = new HashSet<off_question_version>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string html_content { get; set; }
        public string markdown_content { get; set; }
        public string file_question { get; set; }
        public string file_correct_answer { get; set; }
        public Nullable<byte> active { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<byte> request { get; set; }
        public System.DateTime create_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_question> exam_question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examinee_answer> examinee_answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<off_question_map_t2> off_question_map_t2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<off_question_version> off_question_version { get; set; }
    }
}
